# Why-3 Template

WHY3_PACKAGE= name
WHY3_VERSION= x.y.z
WHY3_DEPENDS= pkg ...
WHY3_MODULES= m.M ...
WHY3_EXTRACT= m.M ...

# Documentation
WHY3_TITLE='...'
WHY3_STYLE= f.css

# Include Why-3 Makefile
include $(shell ocamlfind query why3-make)/Makefile.why3
