# Why-3 Template

WHY3_PACKAGE=pkg
WHY3_VERSION=0.1
WHY3_DEPENDS= # pkg ...
WHY3_MODULES= # m ...
WHY3_EXTRACT= # m.M ...

# Documentation
WHY3_TITLE="..."
WHY3_STYLE=

# Include Why-3 Makefile
include $(shell ocamlfind query why3-make)/Makefile.why3
