  $ why3find doc mypkg -o foo
  $ why3find install --dune --doc foo mypkg
  install (source)   mypkg/foo.mlw
  install (html)     html/_mypkg.foo.html
  install (html)     html/icofont.min.css
  install (html)     html/script.js
  install (html)     html/mypkg.foo.html
  install (html)     html/mypkg.foo.T.html
  install (html)     html/style.css
  install (html)     html/mypkg.foo.S.html
  install (html)     html/fonts/icofont.woff2
  install (html)     html/fonts/icofont.woff
  install (meta)     META.json
  Generated ./dune
  $ cat dune
  ;; generated by why3find
  (install
    (package mypkg)
    (section (site (why3find packages)))
    (files
      (META.json as mypkg/META.json)
      (mypkg/foo.mlw as mypkg/mypkg/foo.mlw)
      (foo/_mypkg.foo.html as mypkg/html/_mypkg.foo.html)
      (foo/icofont.min.css as mypkg/html/icofont.min.css)
      (foo/script.js as mypkg/html/script.js)
      (foo/mypkg.foo.html as mypkg/html/mypkg.foo.html)
      (foo/mypkg.foo.T.html as mypkg/html/mypkg.foo.T.html)
      (foo/style.css as mypkg/html/style.css)
      (foo/mypkg.foo.S.html as mypkg/html/mypkg.foo.S.html)
      (foo/fonts/icofont.woff2 as mypkg/html/fonts/icofont.woff2)
      (foo/fonts/icofont.woff as mypkg/html/fonts/icofont.woff)
      ))
