  $ export BUILD_PATH_PREFIX_MAP="WHERE=`why3find where`:$BUILD_PATH_PREFIX_MAP"
  $ why3find extract -l zarith jazz.foo.Bar
  Generated $TESTCASE_ROOT/lib/dune
  $ find lib | sort
  lib
  lib/dune
  lib/jazz__foo__Bar.ml
  $ cat lib/dune
  ;; Generated by why3find extract
  (library
    (name jazz)
    (public_name jazz)
    (wrapped false)
    (libraries zarith))
  $ cat lib/jazz__foo__Bar.ml
  type t =
    | A of (Z.t)
    | B of (bool)
  
  $ why3find install --global jazz
  install (source)   jazz/foo.mlw
  install (meta)     META.json
  Installed WHERE/jazz
  Warning: extracted code not installed (use dune)
  $ why3find query jazz
  Package jazz:
    path: WHERE/jazz
    extracted: yes
  $ find `why3find query jazz -p` | sort
  WHERE/jazz
  WHERE/jazz/META.json
  WHERE/jazz/jazz
  WHERE/jazz/jazz/foo.mlw
  $ why3find uninstall jazz
  remove WHERE/jazz
